@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

actor "ServiceStarter" as serviceStarter
participant "CoinInitializer" as coinInitializer #9EA0CA
collections "CoinActors" as coinActors #3768BB

serviceStarter -> coinInitializer: starting arbitrage service

activate coinInitializer

    loop number of coin:exchange pairs

        coinInitializer -> coinActors: /create-actor-event

        coinActors --> coinInitializer: Coin Actor Created

    end

    coinInitializer --> serviceStarter: All Coin Actors Created

deactivate coinInitializer

@enduml
