@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

participant "Data Aggregator Service" as aggregator
participant "ArbitrageController" as controller #9EA0CA
collections "CoinActors" as coinActors #3768BB
participant "NotificationActor" as notification #9EA0CA
actor "Subscribed User" as user

aggregator -> controller: [gRPC] /coin-update-from-exchange

activate controller
    controller -->aggregator: gRPC Coin Update Received
    activate coinActors
        loop number of coin:exchange pairs
            controller -> coinActors: [Akka event] /coin-price-update
            coinActors --> controller: Akka event received
        end
    deactivate coinActors
deactivate controller

loop total combinations of trading coin pairs
    coinActors -> coinActors: [Akka event] /find-trading-path
    activate coinActors
        alt successful case
            coinActors -> notification: [Akka event] /send-trading-path
            activate notification

                notification --> coinActors: Akka event received

                notification -> user: Send email about trading path
                user --> notification: Email received
            deactivate
        end
    deactivate
end


@enduml
