@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

!global $EXISTING_SYSTEM_BG_COLOR = "#999999"
!global $EXISTING_SYSTEM_BORDER_COLOR = "#8A8A8A"

!unquoted procedure System_Existing($alias, $label, $descr="", $sprite="", $tags="")
rectangle "$getSystem($label, $descr, $sprite)$getProps()" $toStereos("external system", $tags) as $alias
!endprocedure

UpdateSkinparamsAndLegendEntry("external system", $bgColor=$EXISTING_SYSTEM_BG_COLOR, $fontColor=$COLOR_NEUTRAL, $borderColor=$EXISTING_SYSTEM_BORDER_COLOR)

System_Existing(exchanges, "Crypto Exchanges", "Supported exchanges: CEX.IO")
System_Boundary(c1, "Botocrypt Platform") {
    System(botocrypt, "Botocrypt Application", "Collects and process cryptocurrency prices fetched from external crypto exchanges and finds the best opportunities on the market to exploit price differentials between them")
}
Person(consumer, "Botocrypt consumer", "User who is subscribed to Botocrypt platform")

Rel_L(botocrypt, exchanges, "Fetch crypto prices from echanges", "HTTPS")
Rel_R(botocrypt, consumer, "Sends e-mail regarding opportunity")

@enduml
